kernel/Sched: core: fix build after commit 171ca60
Without this patch in my case

Clang outputs error msg:
  CC      sound/soc/soc-ops.o
  CC      drivers/clk/clk-fixed-factor.o
  CC      fs/exfat/extent.o
../kernel/sched/core.c:1225:39: error: use of undeclared identifier 'new_mask'; did you mean 'req_mask'?
        if ((p->flags & PF_PERF_CRITICAL) && new_mask != cpu_lp_mask &&
                                             ^~~~~~~~
                                             req_mask
../kernel/sched/core.c:1222:24: note: 'req_mask' declared here
        const struct cpumask *req_mask)
                              ^
../kernel/sched/core.c:1226:3: error: use of undeclared identifier 'new_mask'; did you mean 'req_mask'?
                new_mask != cpu_perf_mask)
                ^~~~~~~~
                req_mask
../kernel/sched/core.c:1222:24: note: 'req_mask' declared here
        const struct cpumask *req_mask)
                              ^
  CC      drivers/char/diag/diagmem.o
../kernel/sched/core.c:1227:10: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'const struct cpumask *' [-Werror,-Wint-conversion]
                return -EINVAL;
                       ^~~~~~~

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>