Qcacld-3.0/qca-wifi-host-cmn: Squash update
staging: qcacld-3.0: Fix Kconfig

* Correct badly named options
* Add missing options

Change-Id: I4a5cc2216fe36a07520827cdb9577a75ec09450a
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

staging: qcacld-3.0: fix an inconsistency between userspace and kernel options

Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Change-Id: Ic8f571b9a948e81a0d1d282830007632a2b2c6c2
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

staging: qcacld-3.0: add sme_power_save_api.h include

Change-Id: Ic5c408a59ea0f859393fbc6e3f6ba6f0c391df43
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

staging: qcacld-3.0: load driver on late initcall when not built as a module

Requiring userspace to write to /sys/kernel/boot_wlan/boot_wlan to boot
up the wlan device is unnecessary and blocks userspace for the large
amount of time it takes for wlan boot to finish.

Instead, load the driver asynchronously on late_initcall.

Change-Id: I4d696b9d46de032158fd223c60d9a7dbde26cc3f
Signed-off-by: Sultanxda <sultanxda@gmail.com>
[nc: Fix unused variable function warning]
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

staging: qcacld-3.0: load driver at device_initcall

The earlier, the better.

Change-Id: Iae43260050117d7b464dd3c7f47bf8093941a274
Signed-off-by: Sultanxda <sultanxda@gmail.com>
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

staging: qcacld-3.0: fix build after disabling debug

../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_tx_rx.c:1569:45: error: expected expression
                hdd_debug("LRO and GRO both are disabled");
                                                          ^
1 error generated.

Convert to a normal if-else statement

Change-Id: Ia210044d6d6103a1120f0e5fdb74b88ff28d8fc8
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

Revert "qcacld-3.0: Fix OOB in wma_stats_event_handler"

* This change makes WiFi report invalid signal strength.

This reverts commit be468730d315e973e9936da275b06600d0ce276c.

Change-Id: I01094049520ea706c27e00f316539f9d9d53bbc7
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

staging: qcacld-3.0: make debug functions configurable

Change-Id: If0643fc66aac1846fc5e1466d047ff31a5b175c3
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: Enable WLAN_WARN_ON_ASSERT for debug builds

QDF_ASSERT is being featurized in
I39e3ab6499210569b6ce09d77ee72f0081741989. Enable the QDF_ASSERT feature
in debug builds by default.

Change-Id: I96484e6dbebcecf17ae7877dc30906ed8fa90bd7
CRs-Fixed: 2211987
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: Use bundled configuration for inline build too

Change-Id: I38dbec2f7407da60d2c0ea1781c871c67c775a2f
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: Disable build tag for inline build

 * Broken, and only serves to waste build time

Change-Id: I6d0f576b8688619242257a537b8ad5cbe0f2abe9
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: Nuke as much debug bloat as possible

The overhead from all the debugging in this monstrosity of a driver is
measurably significant. Chop it all out.

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>
Signed-off-by: Subhajeet Muhuri <kenny3fcb@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: Add packet capture feature option into Kconfig

* After LA.UM.7.2.r1-07000-sdm660.0 merge.

Signed-off-by: Albert I <kras@raphielgang.org>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

staging: qcacld-3.0: Cleanup unused file

Change-Id: I23d65bc818a13496ffcebefa8e27a167521857f2
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

Revert "qcacld-3.0: Don't fill any WMA request if target is not ready"

This reverts commit 90440e88db493efb6a302ce4aee536f0a83f550e.

Change-Id: I3d54b010da265c381ea2152b6e38ea5a5a986759
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: Disable Wifi SAE by default

This causes significantly reduced throughput when close to access
points, and causes the WiFi connection to drop entirely when slightly
far away from access points during periods of high traffic (e.g.,
running a speed test while not standing next to the access point causes
WiFi to disconnect).

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: optimize for size

- Add -Os flag.
- Add -g0, drops most of the debug that we don't really care about.

Saves about 120kb, which isn't much, but appretiated anyway.

Signed-off-by: Yaroslav Furman <yaro330@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: Do not force the compilation of DFS debugging

Signed-off-by: Tyler Nijmeh <tylernij@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

Staging: Qcacld-3.0/qca-wifi-host-cmn: Checkout AtomX kernel changes

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld: nuke rx_wakelock code entirely

We're not allowing this to be configurable on this kernel.

Nuke this entirely to reduce resource usage.

Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
Signed-off-by: celtare21 <celtare21@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: disable some debugging features

Signed-off-by: kdrag0n <dragon@khronodragon.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: Free a bunch of pkts at once

It is too bad to do a tight loop every adding pkt. When the hotspot is turned on, I notice that the
htt_htc_misc_pkt_list_trim() function consumes at least 5% of CPU time. By caching the head of pkt
queue and freeing multiple pkts at once to reduce CPU consumption.

Signed-off-by: Julian Liu <wlootlxt123@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: disable debugfs & wifi logging

Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: Do not allow any wakelocks to be held

These contribute to a great amount of idle drain.

Tests: 30 minutes of playing Spotify with the screen off, unplugged.

Signed-off-by: Tyler Nijmeh <tylernij@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>