[Squash] Input: Touchscreen: Remove unused functions and cleanup
kgsl: set log level 0

Signed-off-by: sohamxda7 <sensoham135@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

drivers: input: touchscreen: nvt_touch_a/d2s/e7s: disable debugging and ESD check

Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

drivers: input: touchscreen: synaptics_dsx_e7s: disable debugging

Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

drivers: input: touchscreen: ft8719: Disable pressure reporting

 * Disabling pressure reporting in multitouch fixes ghost touches
Change-Id: I85407b08dfe84572b920b9415cfc783a041aac27

Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

touchscreen: use freezable, high priority & unbound workqueues

Signed-off-by: psndna88 <psndna88@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

touchscreen: mark irq handlers as PERF_CRITICAL

Signed-off-by: psndna88 <psndna88@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

NVT-ts: Debloat the driver

* Disable ESD checking
* Disable driver debugging
* Don't build the testing driver

Signed-off-by: Yasir-Siddiqui <www.mohammad.yasir.s@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

nvt_touch_f7a: Eliminate ESD checks

We never want to check for ESD. It increases latency during screen
on/off triggers, and Google even disables it.

Signed-off-by: Yasir-Siddiqui <www.mohammad.yasir.s@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

nvt_touch_f7a: Remove MP CTRLRAM support

Most of this is debugging or hardware testing. We really don't need to
bother with that.

Signed-off-by: Yasir-Siddiqui <www.mohammad.yasir.s@gmail.com>
Signed-off-by: Ratoriku <a1063021545@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

nvt_touch_f7a: Remove earlysuspend support

Truthfully, hardly any modern devices support earlysuspend anymore
instead of FB. We can just remove this filler code.

Signed-off-by: Yasir-Siddiqui <www.mohammad.yasir.s@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

nvt_touch_f7a: Use PROTOCOL_B

Signed-off-by: Yasir-Siddiqui <www.mohammad.yasir.s@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

nvt_touch_f7a: Remove useless #if 0 checks

Signed-off-by: Yasir-Siddiqui <www.mohammad.yasir.s@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

touchscreen: Mark IRQs as performance critical

Touch latency is pretty important; let's service the touch IRQs and
associated kthreads on fast CPUs to improve touch responsiveness.

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>
[wight554: adapted wahoo ts change for synaptics_dsx_force]
Signed-off-by: Volodymyr Zhdanov <wight554@gmail.com>
[Ratoriku: adapted for lavender]
Signed-off-by: Ratoriku <a1063021545@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

touchscreen: Eliminate ESD checks

We never want to check for ESD. It increases latency during screen
on/off triggers, and Google even disables it.

Co-authored-by: Tyler Nijmeh <tylernij@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

touchscreen: Remove MP CTRLRAM support

Most of this is debugging or hardware testing. We really don't need to
bother with that.

Co-authored-by: Tyler Nijmeh <tylernij@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

touchscreen: Remove earlysuspend support

Truthfully, hardly any modern devices support earlysuspend anymore
instead of FB. We can just remove this filler code.

Co-authored-by: Tyler Nijmeh <tylernij@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

touchscreen: Use PROTOCOL_B

Co-authored-by: Tyler Nijmeh <tylernij@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

focal_ft8719: Eliminate ESD checks

Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

touchscreen: Remove useless #if 0 checks

Co-authored-by: Tyler Nijmeh <tylernij@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

treewide: Nuke ESD_TE_status

Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

drivers: touchscreen: nvt: Properly arrange variables to disable firmware update

* This is needed because Init_BootLoader and Resume_PD is needed
  regardless in nt36xxx_ext_proc while the whole fw_update file
  is ifdef'd with BOOT_UPDATE_FIRMWARE
* Fixes this error when building with BOOT_UPDATE_FIRMWARE disabled:

drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.o: In function `nvt_get_oem_data':
drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.c:624: undefined reference to `Init_BootLoader'
drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.c:630: undefined reference to `Resume_PD'
drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.c:624: undefined reference to `Init_BootLoader'

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

drivers: touchscreen: nvt: Properly arrange variables to disable firmware update

* This is needed because Init_BootLoader and Resume_PD is needed
  regardless in nt36xxx_ext_proc while the whole fw_update file
  is ifdef'd with BOOT_UPDATE_FIRMWARE
* Fixes this error when building with BOOT_UPDATE_FIRMWARE disabled:

drivers/input/touchscreen/nvt_touch_a/nt36xxx_ext_proc.o: In function `nvt_get_oem_data':
drivers/input/touchscreen/nvt_touch_a/nt36xxx_ext_proc.c:624: undefined reference to `Init_BootLoader'
drivers/input/touchscreen/nvt_touch_a/nt36xxx_ext_proc.c:630: undefined reference to `Resume_PD'
drivers/input/touchscreen/nvt_touch_a/nt36xxx_ext_proc.c:624: undefined reference to `Init_BootLoader'

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

drivers: touchscreen: nvt: Disable firmware update

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

drivers: touchscreen: nvt: Disable proc support

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

drivers: touchscreen: nvt: clean up and optimize work related functions

Signed-off-by: Tyler Nijmeh <tylernij@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>